secrets:
  secrets_env:
    file: .env

services:
  pung-db:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    image: pung-database:latest
    container_name: pung-db
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      GAME_CORE_DB: "${GAME_CORE_DB}"
      GAME_CORE_DB_USER: "${GAME_CORE_DB_USER}"
      GAME_CORE_DB_PASS: "${GAME_CORE_DB_PASS}"
      GUARDIAN_DB: "${GUARDIAN_DB}"
      GUARDIAN_DB_USER: "${GUARDIAN_DB_USER}"
      GUARDIAN_DB_PASS: "${GUARDIAN_DB_PASS}"
      USER_SESSION_DB: "${USER_SESSION_DB}"
      USER_SESSION_DB_USER: "${USER_SESSION_DB_USER}" 
      USER_SESSION_DB_PASS: "${USER_SESSION_DB_PASS}"
    volumes:
      - ./database/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - pung-db-data:/var/lib/postgresql/data
    secrets:
      - secrets_env

volumes:
  pung-db-data:
    name: pung-db-data
