#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $GAME_CORE_DB;
    CREATE DATABASE $GUARDIAN_DB;
    CREATE DATABASE $USER_SESSION_DB;

    CREATE USER $GAME_DB_USER WITH PASSWORD '$GAME_DB_PASS';
    CREATE USER $GUARDIAN_DB_USER WITH PASSWORD '$GUARDIAN_DB_PASS';
    CREATE USER $USER_SESSION_DB_USER WITH PASSWORD '$USER_SESSION_DB_PASS';

    GRANT ALL PRIVILEGES ON DATABASE $GAME_CORE_DB TO $GAME_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $GUARDIAN_DB TO $GUARDIAN_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $USER_SESSION_DB TO $USER_SESSION_DB_USER;
EOSQL

